### PR TITLE
Add IsAlive to the Core interface

### PR DESCRIPTION
**Pull request by roignpar**
For https://github.com/ipfs/iptb/issues/112.

### CODE REVIEW

**Comment by Stebalien** [comment]
(blocked on implementations in https://github.com/ipfs/iptb-plugins)

**Comment by roignpar** [comment]
I will try to add the plugin implementations as well.

**Comment by roignpar** [comment]
Regarding the plugin implementations, is it enough to simply set a field, e.g. `BrowserIpfs.alive` to `true` if `Start` is successful and `false` when `Stop` is called?

Is it better to have a specific implementation for each plugin? e.g. in the case of `BrowserIpfs` make an API call to see if a response is received, for `DockerIpfs` check that the container is running, etc.

Or maybe some other solution?

**Comment by Stebalien** [comment]
@bigs or @travisperson thoughts?

**Comment by bigs** [comment]
@roignpar @Stebalien i think this would be quite useful. i'd even go so far as to integrate it into the CLI, so you can poll status of nodes. would you want to add some notion of health checking?

**Comment by travisperson** [comment]
The `IsAlive` should verify that the process is still running. It can't be set / unset in `Start` and `Stop` because iptb process does not live the entire length of the underlying node process.

The implementation can be independent per plugin, but can be shared if they are the same. Currently liveliness checks are done by checking if the API is reachable and I think it's an okay solution, and I'd probably say that the implementation notes for the interface method `IsAlive` should state something to the effect of "When IsAlive returns true, calls to RunCmd can be made".

> i'd even go so far as to integrate it into the CLI, so you can poll status of nodes.

One of the things I'd really like to do is place a warning when force overriding a testbed config. It's pretty common to accidentally override a config with nodes still running.

**Comment by roignpar** [comment]
@bigs @travisperson 
I agree that it would be useful to add a `status` (or something similar) API endpoint and CLI command, but that is a bigger change and goes outside the scope of this issue in my opinion.

I believe that making a call to `/api/v0/version` and verifying that the response is `200` is enough for `IsAlive`. Only `localp2pd` needs a different approach as far as I can tell.
What do you think?

**Pull request closed without merging**
