### PR TITLE
Update import paths, enable ci

### PR DESCRIPTION
**Pull request by magik6k**

### CODE REVIEW

**Comment by Stebalien** [comment]
@VictorBjelkholm does anything need to be done to actually enable jenkins (or should we stick with travis for now)?

**Comment by magik6k** [comment]
Afaik the ci team needs write access to the repo, though the tests don't pass currently: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fiptb/detail/PR-47/3/pipeline/9, 

```
util/localnode.go:17:2: cannot find package "github.com/ipfs/go-ipfs/repo/config" in any of:
	/tmp/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.9.2/src/github.com/ipfs/go-ipfs/repo/config (from $GOROOT)
	/tmp/jenkins/workspace/IPFS_iptb_PR-47-MHXBXZQR7DMONLHKFMKLPUHKFTT4ULIXW66A7RKN56VZKFY673EA/src/github.com/ipfs/go-ipfs/repo/config (from $GOPATH)
util/localnode.go:18:2: cannot find package "github.com/ipfs/go-ipfs/repo/fsrepo/serialize" in any of:
	/tmp/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.9.2/src/github.com/ipfs/go-ipfs/repo/fsrepo/serialize (from $GOROOT)
	/tmp/jenkins/workspace/IPFS_iptb_PR-47-MHXBXZQR7DMONLHKFMKLPUHKFTT4ULIXW66A7RKN56VZKFY673EA/src/github.com/ipfs/go-ipfs/repo/fsrepo/serialize (from $GOPATH)
```

I wanted to extract repo stuff from go-ipfs earlier for ds-convert, so it needs to be done anyways

**Comment by magik6k** [comment]
It also looks like jenkins fails to mark failed compilation as failed, reported in https://github.com/ipfs/jenkins/issues/96

**Comment by magik6k** [comment]
Will fix ci in another PR

**Pull request merged**
